UPDATE mytable set Nazwa_Muzeum =  "	Centralne Muzeum Jeńców Wojennych w Łambinowicach - Opolu 	" WHERE Lp=	1	;
UPDATE mytable set Nazwa_Muzeum =  "	Centralne Muzeum Pożarnictwa w Mysłowicach	" WHERE Lp=	2	;
UPDATE mytable set Nazwa_Muzeum =  "	Centralne Muzeum Włókiennictwa w Łodzi	" WHERE Lp=	3	;
UPDATE mytable set Nazwa_Muzeum =  "	Interaktywne Muzeum Państwa Krzyżackiego w Działdowie  	" WHERE Lp=	4	;
UPDATE mytable set Nazwa_Muzeum =  "	Lubuskie Muzeum Wojskowe w Zielonej Górze z siedzibą w Drzonowie 	" WHERE Lp=	5	;
UPDATE mytable set Nazwa_Muzeum =  "	Miejskie Muzeum Zabawek ze zbiorów Henryka Tomaszewskiego	" WHERE Lp=	6	;
UPDATE mytable set Nazwa_Muzeum =  "	Międzyrzecki Rejon Umocniony - Muzeum Fortyfikacji i Nietoperzy w Pniewie 	" WHERE Lp=	7	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czartoryskich w Puławach (w organizacji)	" WHERE Lp=	8	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum „Górnośląski Park Etnograficzny w Chorzowie”	" WHERE Lp=	9	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne w Biskupinie	" WHERE Lp=	10	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne w Gdańsku	" WHERE Lp=	11	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne w Krakowie	" WHERE Lp=	12	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne w Poznaniu	" WHERE Lp=	13	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne i Etnograficzne w Łodzi	" WHERE Lp=	14	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczne Środkowego Nadodrza w Zielonej Górze z siedzibą w Świdnicy	" WHERE Lp=	15	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczno-Historyczne w Elblągu	" WHERE Lp=	16	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczno-Historyczne w Głogowie	" WHERE Lp=	17	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologiczno – Historyczne w Stargardzie 	" WHERE Lp=	18	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Architektury we Wrocławiu	" WHERE Lp=	19	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Armii Krajowej im. gen. Emila Fieldorfa ,,Nila” w Krakowie	" WHERE Lp=	20	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Augusta Zamoyskiego w Jabłoniu 	" WHERE Lp=	21	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Azji i Pacyfiku w Warszawie	" WHERE Lp=	22	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Bitwy pod Grunwaldem w Stębarku	" WHERE Lp=	23	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Budownictwa Ludowego – Park Etnograficzny w Olsztynku	" WHERE Lp=	24	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Budownictwa Ludowego w Sanoku	" WHERE Lp=	25	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ceramiki w Bolesławcu	" WHERE Lp=	26	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Częstochowskie	" WHERE Lp=	27	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dawnego Kupiectwa w Świdnicy	" WHERE Lp=	28	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dobranocek ze Zbiorów Wojciecha Jamy w Rzeszowie	" WHERE Lp=	29	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dulag 121	" WHERE Lp=	30	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Dwory Karwacjanów i Gładyszów	" WHERE Lp=	31	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Emigracji w Gdyni                                              	" WHERE Lp=	32	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Etnograficzne w Zielonej Górze z siedzibą w Ochli	" WHERE Lp=	33	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Etnograficzne im. Marii Znamierowskiej - Prüfferowej w Toruniu	" WHERE Lp=	34	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Etnograficzne im. Seweryna Udzieli w Krakowie	" WHERE Lp=	35	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fauny i Flory Morskiej i Śródlądowej w Jaworzu	" WHERE Lp=	36	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Filumenistyczne w Bystrzycy Kłodzkiej	" WHERE Lp=	37	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gminne w Biszczy	" WHERE Lp=	38	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Górnictwa Węglowego w Zabrzu	" WHERE Lp=	39	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Górnośląskie w Bytomiu	" WHERE Lp=	40	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gross-Rosen w Rogoźnicy	" WHERE Lp=	41	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Henryka Sienkiewicza w Woli Okrzejskiej	" WHERE Lp=	42	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Fotografii im. Walerego Rzewuskiego w Krakowie	" WHERE Lp=	43	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Katowic w Katowicach	" WHERE Lp=	44	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Kielc	" WHERE Lp=	45	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Miasta Zduńska Wola	" WHERE Lp=	46	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Polskiego Ruchu Ludowego w Warszawie	" WHERE Lp=	47	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Przemysłu w Opatówku	" WHERE Lp=	48	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Ziemi Kamieńskiej	" WHERE Lp=	49	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Miasta Gdańska	" WHERE Lp=	50	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Miasta Krakowa	" WHERE Lp=	51	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Miasta Tarnobrzega	" WHERE Lp=	52	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne - Pałac w Dukli	" WHERE Lp=	53	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Bielsku-Białej	" WHERE Lp=	54	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Ełku  (w organizacji)	" WHERE Lp=	55	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Legionowie	" WHERE Lp=	56	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Lubinie (w organizacji)	" WHERE Lp=	57	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Przasnyszu (w organizacji)	" WHERE Lp=	58	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Sanoku	" WHERE Lp=	59	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczno-Archeologiczne w Ostrowcu Świętokrzyskim	" WHERE Lp=	60	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczno-Etnograficzne im. Juliana Rydzkowskiego w Chojnicach	" WHERE Lp=	61	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Aleksandra Kłosińskiego w Kętach	" WHERE Lp=	62	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Anny i Jarosława Iwaszkiewiczów w Stawisku	" WHERE Lp=	63	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Jacka Malczewskiego w Radomiu	" WHERE Lp=	64	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Jana Dzierżona w Kluczborku	" WHERE Lp=	65	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Jana Kasprowicza w Inowrocławiu" WHERE Lp=	66	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Jerzego Dunin-Borkowskiego  w Krośniewicach	" WHERE Lp=	67	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Kazimierza Pułaskiego w Warce 	" WHERE Lp=	68	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. ks. dr. Władysława Łęgi w Grudziądzu	" WHERE Lp=	69	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. ks. Stanisława Staszica w Hrubieszowie	" WHERE Lp=	70	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. ,,Orła Białego” w Skarżysku - Kamiennej	" WHERE Lp=	71	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. prof. Stanisława Fischera w Bochni	" WHERE Lp=	72	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Przypkowskich w Jędrzejowie	" WHERE Lp=	73	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Władysława Orkana w Rabce - Zdroju	" WHERE Lp=	74	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Wojciecha Kętrzyńskiego w Kętrzynie	" WHERE Lp=	75	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Zofii i Wacława Nałkowskich w Wołominie	" WHERE Lp=	76	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Inżynierii Miejskiej w Krakowie	" WHERE Lp=	77	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Józefa Ignacego Kraszewskiego  w Romanowie	" WHERE Lp=	78	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Karkonoskie w Jeleniej Górze	" WHERE Lp=	79	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Karykatury im. Eryka Lipińskiego w Warszawie	" WHERE Lp=	80	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Kaszubski Park Etnograficzny im. Teodory i Izydora Gulgowskich  we Wdzydzach Kiszewskich	" WHERE Lp=	81	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kaszubskie im. Franciszka Tredera w Kartuzach	" WHERE Lp=	82	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kinematografii w Łodzi	" WHERE Lp=	83	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Konstantego Ildefonsa Gałczyńskiego w Praniu z Oddziałem Muzeum Michała Kajki w Ogródku 	" WHERE Lp=	84	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kresów w Lubaczowie	" WHERE Lp=	85	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kultury Kurpiowskiej w Ostrołęce	" WHERE Lp=	86	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kultury Ludowej Pogórza Sudeckiego w Kudowie - Zdroju	" WHERE Lp=	87	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kultury Ludowej w Kolbuszowej	" WHERE Lp=	88	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kultury Ludowej w Węgorzewie	" WHERE Lp=	89	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lniarstwa im. Filipa De Girarda  w Żyrardowie (w organizacji)	" WHERE Lp=	90	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lotnictwa Polskiego w Krakowie	" WHERE Lp=	91	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lubuskie im. Jana Dekerta w Gorzowie Wielkopolskim	" WHERE Lp=	92	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ludowych Instrumentów Muzycznych w Szydłowcu	" WHERE Lp=	93	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Łużyckie w Zgorzelcu	" WHERE Lp=	94	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Marii Konopnickiej w Żarnowcu	" WHERE Lp=	95	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Martyrologiczne w Żabikowie	" WHERE Lp=	96	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Mazowieckie w Płocku	" WHERE Lp=	97	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Mazowsza Zachodniego w Żyrardowie  	" WHERE Lp=	98	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Gdyni	" WHERE Lp=	99	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Jaworzna	" WHERE Lp=	100	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Łodzi	" WHERE Lp=	101	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Mysłowice	" WHERE Lp=	102	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Ostrowa Wielkopolskiego	" WHERE Lp=	103	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Pabianic	" WHERE Lp=	104	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Turku im. Józefa Mehoffera	" WHERE Lp=	105	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Zgierza	" WHERE Lp=	106	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miedzi w Legnicy	" WHERE Lp=	107	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie Dzierżoniowa  	" WHERE Lp=	108	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Nowej Soli	" WHERE Lp=	109	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Siemianowicach Śląskich	" WHERE Lp=	110	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie Suchej Beskidzkiej	" WHERE Lp=	111	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Tychach	" WHERE Lp=	112	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Zabrzu	" WHERE Lp=	113	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Żorach	" WHERE Lp=	114	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Żywcu	" WHERE Lp=	115	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie Dom Gerharta Hauptmanna  w Jeleniej Górze	" WHERE Lp=	116	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie Sztygarka w Dąbrowie Górniczej	" WHERE Lp=	117	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie im. Maksymiliana Chroboka w Rudzie Śląskiej	" WHERE Lp=	118	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie Wrocławia	" WHERE Lp=	119	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Mikołaja Kopernika we Fromborku	" WHERE Lp=	120	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Nadwiślański Park Etnograficzny w Wygiełzowie i Zamek Lipowiec	" WHERE Lp=	121	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Nadwiślańskie  w Kazimierzu Dolnym	" WHERE Lp=	122	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe Rolnictwa i Przemysłu Rolno-Spożywczego w Szreniawie	" WHERE Lp=	123	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe Ziemi Przemyskiej w Przemyślu	" WHERE Lp=	124	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Niepodległości w Warszawie	" WHERE Lp=	125	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Niepołomickie w Niepołomicach	" WHERE Lp=	126	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Obozów Jenieckich w Żaganiu 	" WHERE Lp=	127	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe im. Leona Wyczółkowskiego w Bydgoszczy	" WHERE Lp=	128	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe im. Stanisława Staszica w Pile	" WHERE Lp=	129	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Koninie	" WHERE Lp=	130	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Lesznie	" WHERE Lp=	131	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Nowym Sączu	" WHERE Lp=	132	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Rzeszowie	" WHERE Lp=	133	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Sandomierzu	" WHERE Lp=	134	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Sieradzu	" WHERE Lp=	135	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Suwałkach	" WHERE Lp=	136	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Tarnowie	" WHERE Lp=	137	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe w Toruniu	" WHERE Lp=	138	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Okręgowe Ziemi Kaliskiej w Kaliszu	" WHERE Lp=	139	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Orawski Park Etnograficzny  w Zubrzycy Górnej	" WHERE Lp=	140	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża Polskiego w Kołobrzegu	" WHERE Lp=	141	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pamięci Narodowej i Sztuki Ludowej w Ochotnicy Górnej  (w organizacji)	" WHERE Lp=	142	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pamiątek 1. Armii Wojska Polskiego oraz Dziejów Ziemi Mieszkowickiej w Mieszkowicach	" WHERE Lp=	143	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pamięci Sybiru - Muzeum w organizacji	" WHERE Lp=	144	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Papiernictwa w Dusznikach Zdroju	" WHERE Lp=	145	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pierwszych Piastów na Lednicy	" WHERE Lp=	146	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Piśmiennictwa i Muzyki Kaszubsko-Pomorskiej w Wejherowie	" WHERE Lp=	147	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Początków Państwa Polskiego  w Gnieźnie	" WHERE Lp=	148	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Poczty i Telekomunikacji we Wrocławiu	" WHERE Lp=	149	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Podkarpackie w Krośnie	" WHERE Lp=	150	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Podlaskie w Białymstoku	" WHERE Lp=	151	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pogranicza Śląsko – Łużyckiego w Żarach 	" WHERE Lp=	152	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pojezierza Łęczyńsko-Włodawskiego we Włodawie	" WHERE Lp=	153	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pojezierza Myśliborskiego w Myśliborzu	" WHERE Lp=	154	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Polskiej Piosenki w Opolu  (w organizacji)	" WHERE Lp=	155	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Południowego Podlasia w Białej Podlaskiej	" WHERE Lp=	156	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pomorza Środkowego w Słupsku	" WHERE Lp=	157	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Powstania Warszawskiego	" WHERE Lp=	158	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Powstań Śląskich w Świętochłowicach 	" WHERE Lp=	159	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pożarnictwa w Oseredku 	" WHERE Lp=	160	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Północno – Mazowieckie w Łomży	" WHERE Lp=	161	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przyrodnicze w Jeleniej Górze	" WHERE Lp=	162	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przyrody w Drozdowie	" WHERE Lp=	163	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przyrody i Techniki Ekomuzeum im. Jana Pazdura w Starachowicach	" WHERE Lp=	164	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Puszczy Drawskiej i Noteckiej im. Franciszka Grasia w Drezdenku	" WHERE Lp=	165	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Adama Fastnachta w Brzozowie	" WHERE Lp=	166	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. dr. Henryka Florkowskiego w Kościanie	" WHERE Lp=	167	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. dr. Janusza Petera w Tomaszowie Lubelskim	" WHERE Lp=	168	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Dzieci Wrzesińskich we Wrześni 	" WHERE Lp=	169	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Hieronima Ławniczaka w Krotoszynie	" WHERE Lp=	170	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. prof. Tomasza Mikockiego w Kozienicach	" WHERE Lp=	171	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Stanisława Sankowskiego w Radomsku 	" WHERE Lp=	172	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Walentyny Dermackiej z Sapiehów w Pieckach (w organizacji)	" WHERE Lp=	173	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Wł. St. Reymonta w Lipcach Reymontowskich	" WHERE Lp=	174	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Zygmunta Krasińskiego w Złotym Potoku	" WHERE Lp=	175	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Bełchatowie	" WHERE Lp=	176	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Brzezinach	" WHERE Lp=	177	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Chojnowie	" WHERE Lp=	178	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Człuchowie	" WHERE Lp=	179	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Dębicy	" WHERE Lp=	180	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Gniewkowie	" WHERE Lp=	181	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Janowie Lubelskim	" WHERE Lp=	182	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Jaśle	" WHERE Lp=	183	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Jaworze 	" WHERE Lp=	184	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Kluczkowicach	" WHERE Lp=	185	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Krasnymstawie	" WHERE Lp=	186	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Kutnie	" WHERE Lp=	187	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Lubaniu	" WHERE Lp=	188	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Łukowie	" WHERE Lp=	189	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Opocznie	" WHERE Lp=	190	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Pińczowie	" WHERE Lp=	191	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Pleszewie	" WHERE Lp=	192	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Pułtusku	" WHERE Lp=	193	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Siedlcach	" WHERE Lp=	194	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Skawinie	" WHERE Lp=	195	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Słupcy	" WHERE Lp=	196	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Stalowej Woli	" WHERE Lp=	197	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Stęszewie	" WHERE Lp=	198	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Szczecinku	" WHERE Lp=	199	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Środzie Śląskiej	" WHERE Lp=	200	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Świebodzinie	" WHERE Lp=	201	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Trzebnicy	" WHERE Lp=	202	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Zwoleniu	" WHERE Lp=	203	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne Ziemi Limanowskiej 	" WHERE Lp=	204	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne Ziemi Sulmierzyckiej im. Sebastiana Fabiana Klonowicza	" WHERE Lp=	205	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Rolnictwa im. ks. Krzysztofa Klukaw Ciechanowcu	" WHERE Lp=	206	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Romantyzmu w Opinogórze	" WHERE Lp=	207	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Rzemiosła w Krośnie	" WHERE Lp=	208	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Saturn w Czeladzi	" WHERE Lp=	209	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Solca im. Księcia Przemysła w Solcu Kujawskim	" WHERE Lp=	210	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sopotu	" WHERE Lp=	211	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sportu i Turystyki w Karpaczu	" WHERE Lp=	212	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sportu i Turystyki w Warszawie	" WHERE Lp=	213	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sprzętu Gospodarstwa Domowego w Ziębicach	" WHERE Lp=	214	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Starożytnego Hutnictwa Mazowieckiego im. Stefana Woydy w Pruszkowie	" WHERE Lp=	215	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Szlachty Mazowieckiej w Ciechanowie	" WHERE Lp=	216	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Współczesnej w Krakowie (w organizacji)	" WHERE Lp=	217	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Śląska Cieszyńskiego w Cieszynie	" WHERE Lp=	218	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Śląska Opolskiego w Opolu	" WHERE Lp=	219	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ślężańskie im. Stanisława Dunajewskiego w Sobótce	" WHERE Lp=	220	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ślusarstwa im. Marcina Mikuły w Świątnikach Górnych	" WHERE Lp=	221	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Śremskie w Śremie	" WHERE Lp=	222	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tatrzańskie im. dra Tytusa Chałubińskiego w Zakopanem	" WHERE Lp=	223	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Technik Ceramicznych w Kole	" WHERE Lp=	224	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Komunikacji - Zajezdnia Sztuki w Szczecinie	" WHERE Lp=	225	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tkactwa w Kamiennej Górze	" WHERE Lp=	226	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tradycji Niepodległościowych w Łodzi	" WHERE Lp=	227	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Twierdzy Kostrzyn nad Odrą	" WHERE Lp=	228	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ustrońskie im. Jana Jarockiego w Ustroniu	" WHERE Lp=	229	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Brodnicy	" WHERE Lp=	230	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Chorzowie	" WHERE Lp=	231	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Chrzanowie im. Ireny i Mieczysława Mazarakich	" WHERE Lp=	232	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Gliwicach	" WHERE Lp=	233	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Jarosławiu Kamienica Orsettich	" WHERE Lp=	234	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Koszalinie	" WHERE Lp=	235	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Lewkowie - Zespół Pałacowo - Parkowy 	" WHERE Lp=	236	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Lęborku	" WHERE Lp=	237	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Łęczycy	" WHERE Lp=	238	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Łowiczu	" WHERE Lp=	239	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Powiatowe w Nysie	" WHERE Lp=	240	;
UPDATE mytable set Nazwa_Muzeum =  "	 Muzeum Regionalne w Ostródzie	" WHERE Lp=	241	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Piotrkowie Trybunalskim	" WHERE Lp=	242	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Praszce	" WHERE Lp=	243	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Przeworsku - Zespół Pałacowo-Parkowy	" WHERE Lp=	244	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Raciborzu	" WHERE Lp=	245	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Rybniku	" WHERE Lp=	246	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Tarnowskich Górach	" WHERE Lp=	247	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Tomaszowie Mazowieckim imienia Antoniego Hrabiego Ostrowskiego	" WHERE Lp=	248	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Porcelany w Wałbrzychu	" WHERE Lp=	249	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Wodzisławiu Śląskim	" WHERE Lp=	250	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Warmii i Mazur w Olsztynie	" WHERE Lp=	251	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Warszawy	" WHERE Lp=	252	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojska w Białymstoku 	" WHERE Lp=	253	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojska, Wojskowowści i Ziemi Orzyskiej w Orzyszu w organizacji	" WHERE Lp=	254	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Kieleckiej w Kielcach 	" WHERE Lp=	255	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Lubelskiej w Lublinie	" WHERE Lp=	256	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Mazowieckiej w Sierpcu	" WHERE Lp=	257	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Opolskiej w Opolu	" WHERE Lp=	258	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Radomskiej w Radomiu	" WHERE Lp=	259	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Współczesne Wrocław  (w organizacji)	" WHERE Lp=	260	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zabawek i Zabawy w Kielcach	" WHERE Lp=	261	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zachodniokaszubskie w Bytowie	" WHERE Lp=	262	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zagłębia w Będzinie	" WHERE Lp=	263	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Zamek Górków w Szamotułach	" WHERE Lp=	264	;
UPDATE mytable set Nazwa_Muzeum =  "	Zamek Książąt Pomorskich - Muzeum w Darłowie	" WHERE Lp=	265	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamek Opalińskich w Sierakowie	" WHERE Lp=	266	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Zamek w Oporowie	" WHERE Lp=	267	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamek w Oświęcimiu 	" WHERE Lp=	268	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamkowe w Pszczynie	" WHERE Lp=	269	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamojskie w Zamościu	" WHERE Lp=	270	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamoyskich w Kozłówce	" WHERE Lp=	271	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zbrojownia na Zamku w Liwie	" WHERE Lp=	272	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Bieckiej	" WHERE Lp=	273	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Biłgorajskiej w Biłgoraju	" WHERE Lp=	274	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Chełmskiej im. Wiktora Ambroziewicza w Chełmie	" WHERE Lp=	275	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Dobrzyńskiej w Rypinie 	" WHERE Lp=	276	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Kępińskiej  im. Tadeusza Piotra Potworowskiego w Kępnie 	" WHERE Lp=	277	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Kłodzkiej w Kłodzku	" WHERE Lp=	278	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Koszyckiej im. Stanisława Boducha w Koszycach	" WHERE Lp=	279	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Kościerskiej im. dra Jerzego Knyby w Kościerzynie	" WHERE Lp=	280	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Kozielskiej w Kędzierzynie Koźlu  (w organizacji)	" WHERE Lp=	281	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Krajeńskiej w Nakle nad Notecią	" WHERE Lp=	282	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Kujawskiej i Dobrzyńskiej we Włocławku	" WHERE Lp=	283	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Leżajskiej	" WHERE Lp=	284	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Lubartowskiej w Lubartowie (w organizacji)	" WHERE Lp=	285	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Lubuskiej w Zielonej Górze	" WHERE Lp=	286	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Miechowskiej w Miechowie (w organizacji) 	" WHERE Lp=	287	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Międzyrzeckiej  im. Alfa Kowalskiego 	" WHERE Lp=	288	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Mińskiej w Mińsku Mazowieckim 	" WHERE Lp=	289	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Mogileńskiej w Mogilnie z siedzibą w Chabsku	" WHERE Lp=	290	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Nadnoteckiej im. Wiktora Stachowiaka w Trzciance	" WHERE Lp=	291	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Pałuckiej w Żninie	" WHERE Lp=	292	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Piskiej w Piszu	" WHERE Lp=	293	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Prudnickiej w Prudniku	" WHERE Lp=	294	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Puckiej im. Floriana Ceynowy w Pucku	" WHERE Lp=	295	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Rawickiej w Rawiczu	" WHERE Lp=	296	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Rawskiej w Rawie Mazowieckiej	" WHERE Lp=	297	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Sadowieńskiej w Sadownem	" WHERE Lp=	298	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Szubińskiej im. Zenona Erdmanna w Szubinie	" WHERE Lp=	299	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Średzkiej - „Dwór w Koszutach”	" WHERE Lp=	300	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Wałeckiej w Wałczu	" WHERE Lp=	301	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Wieluńskiej w Wieluniu	" WHERE Lp=	302	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Wiśnickiej w Nowym Wiśniczu	" WHERE Lp=	303	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Wschowskiej 	" WHERE Lp=	304	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Zawkrzeńskiej w Mławie	" WHERE Lp=	305	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Złotowskiej w Złotowie	" WHERE Lp=	306	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemiaństwa w Dobrzycy - Zespół Pałacowo-Parkowy	" WHERE Lp=	307	;
UPDATE mytable set Nazwa_Muzeum =  "	Oleskie Muzeum Regionalne w Oleśnie	" WHERE Lp=	308	;
UPDATE mytable set Nazwa_Muzeum =  "	Pałac Schoena Muzeum w Sosnowcu 	" WHERE Lp=	309	;
UPDATE mytable set Nazwa_Muzeum =  "	Państwowe Muzeum Archeologiczne w Warszawie	" WHERE Lp=	310	;
UPDATE mytable set Nazwa_Muzeum =  "	Państwowe Muzeum Etnograficzne  w Warszawie	" WHERE Lp=	311	;
UPDATE mytable set Nazwa_Muzeum =  "	Podlaskie Muzeum Kultury Ludowej (w organizacji)	" WHERE Lp=	312	;
UPDATE mytable set Nazwa_Muzeum =  "	Powiatowe Muzeum Ziemi Głubczyckiej w Głubczycach	" WHERE Lp=	313	;
UPDATE mytable set Nazwa_Muzeum =  "	Skansen w Sidzinie-Muzeum Kultury Ludowej	" WHERE Lp=	314	;
UPDATE mytable set Nazwa_Muzeum =  "	Wielkopolskie Muzeum Niepodległości	" WHERE Lp=	315	;
UPDATE mytable set Nazwa_Muzeum =  "	Żywiecki Park Etnograficzny Muzeum (w organizacji)	" WHERE Lp=	316	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dom Rodzinny Ojca Świętego Jana Pawła II w Wadowicach	" WHERE Lp=	317	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Dom Rodziny Pileckich w Ostrowi Mazowieckiej (w organizacji) 	" WHERE Lp=	318	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Żydów Polskich	" WHERE Lp=	319	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Jana Pawła II i Prymasa Wyszyńskiego	" WHERE Lp=	320	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Józefa Piłsudskiego w Sulejówku	" WHERE Lp=	321	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Literatury im. Adama Mickiewicza  w Warszawie	" WHERE Lp=	322	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lubelskie w Lublinie	" WHERE Lp=	323	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Gdańsku	" WHERE Lp=	324	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Kielcach	" WHERE Lp=	325	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Szczecinie	" WHERE Lp=	326	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe we Wrocławiu	" WHERE Lp=	327	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Piastów Śląskich w Brzegu	" WHERE Lp=	328	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Polaków Ratujących Żydów podczas II wojny światowej im. Rodziny Ulmów w Markowej 	" WHERE Lp=	329	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum PRL – u  (w organizacji)	" WHERE Lp=	330	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Nowoczesnej w Warszawie	" WHERE Lp=	331	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki w Łodzi	" WHERE Lp=	332	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Śląskie w Katowicach	" WHERE Lp=	333	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum-Zamek w Łańcucie	" WHERE Lp=	334	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Żołnierzy Wyklętych w Ostrołęce (w organizacji)	" WHERE Lp=	335	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum II Wojny Światowej w Gdańsku 	" WHERE Lp=	336	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Polski w Warszawie 	" WHERE Lp=	337	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Łazienki Królewskie w Warszawie	" WHERE Lp=	338	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Łowiectwa i Jeździectwa w Warszawie	" WHERE Lp=	339	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Marynarki Wojennej w Gdyni	" WHERE Lp=	340	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Krakowie	" WHERE Lp=	341	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Poznaniu	" WHERE Lp=	342	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narodowe w Warszawie	" WHERE Lp=	343	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pałacu Króla Jana III w Wilanowie" WHERE Lp=	344	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sił Powietrznych w Dęblinie	" WHERE Lp=	345	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Stutthof w Sztutowie	" WHERE Lp=	346	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki i Techniki Japońskiej MANGGHA 	" WHERE Lp=	347	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojsk Lądowych w Bydgoszczy	" WHERE Lp=	348	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojska Polskiego w Warszawie	" WHERE Lp=	349	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamkowe w Malborku	" WHERE Lp=	350	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Żup Krakowskich Wieliczka w Wieliczce 	" WHERE Lp=	351	;
UPDATE mytable set Nazwa_Muzeum =  "	Narodowe Muzeum Morskie w Gdańsku	" WHERE Lp=	352	;
UPDATE mytable set Nazwa_Muzeum =  "	Państwowe Muzeum Auschwitz-Birkenau w Oświęcimiu	" WHERE Lp=	353	;
UPDATE mytable set Nazwa_Muzeum =  "	Państwowe Muzeum na Majdanku w Lublinie	" WHERE Lp=	354	;
UPDATE mytable set Nazwa_Muzeum =  "	Zamek Królewski na Wawelu – Państwowe Zbiory Sztuki 	" WHERE Lp=	355	;
UPDATE mytable set Nazwa_Muzeum =  "	Zamek Królewski w Warszawie – Muzeum. Rezydencja Królów i Rzeczypospolitej 	" WHERE Lp=	356	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archidiecezjalne Kardynała Karola Wojtyły 	" WHERE Lp=	357	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum bł. Ojca Stanisława Papczyńskiego w Górze Kalwarii	" WHERE Lp=	358	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Diecezjalne w Drohiczynie im. Jana Pawła II	" WHERE Lp=	359	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Diecezjalne w Siedlcach	" WHERE Lp=	360	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Diecezji Elbląskiej	" WHERE Lp=	361	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Księdza Walentego Ślusarczyka przy Opactwie O.O. Cysterów w Wąchocku (w organizacji)	" WHERE Lp=	362	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. św. Jana Pawła II w organizacji 	" WHERE Lp=	363	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Markowieckiego Sanktuarium 	" WHERE Lp=	364	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Misyjne Sióstr Klawerianek w Krośnie	" WHERE Lp=	365	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Prawosławnej Diecezji Lubelsko-Chełmskiej	" WHERE Lp=	366	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Reformacji Polskiej w Mikołajkach	" WHERE Lp=	367	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Warszawskiej Metropolii Prawosławnej w Warszawie 	" WHERE Lp=	368	;
UPDATE mytable set Nazwa_Muzeum =  "	Chojnickie Muzeum Motoryzacji i Techniki (w organizacji)	" WHERE Lp=	369	;
UPDATE mytable set Nazwa_Muzeum =  "	Chotomowskie Muzeum Techniki Wojskowej w Chotomowie	" WHERE Lp=	370	;
UPDATE mytable set Nazwa_Muzeum =  "	Ekomuzeum Olejarstwa w Zadnodze Olejarnia Staropolska na Roztoczu  (w organizacji)	" WHERE Lp=	371	;
UPDATE mytable set Nazwa_Muzeum =  "	Falenickie Muzeum Historyczne (w organizacji)	" WHERE Lp=	372	;
UPDATE mytable set Nazwa_Muzeum =  "	Kolbuszowskie Muzeum Techniki Militarnej i Użytkowej  (w organizacji)	" WHERE Lp=	373	;
UPDATE mytable set Nazwa_Muzeum =  "	Kwidzyńskie Muzeum Rodła  (w organizacji)	" WHERE Lp=	374	;
UPDATE mytable set Nazwa_Muzeum =  "	Lokalne Muzeum Techniki Wojskowej i Cywilnej (w organizacji)	" WHERE Lp=	375	;
UPDATE mytable set Nazwa_Muzeum =  "	Małe Muzeum Ludowe u Kowalskich 	" WHERE Lp=	376	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Afryki w Sobanicach 	" WHERE Lp=	377	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Archeologii Pól Bitewnych Twierdzy Przemyśl w Przemyślu (w organizacji) 	" WHERE Lp=	378	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum – Archeoskansen grodu warownego  z X w. (w organizacji)	" WHERE Lp=	379	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Bohaterów Września 1939 im. Jerzego Waszkiewicza (w organizacji)	" WHERE Lp=	380	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni i Militariów w Lubawie (w organizacji)	" WHERE Lp=	381	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni i Militariów w Przasnyszu (w organizacji)	" WHERE Lp=	382	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni i Wyposażenia Piechoty w Warszawie (w organizacji)	" WHERE Lp=	383	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni w Stanisławowie (w organizacji)	" WHERE Lp=	384	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Bursztynu w Warszawie w organizacji 	" WHERE Lp=	385	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czynu Zbrojnego w Lipcach Reymontowskich	" WHERE Lp=	386	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czynu Zbrojnego Żywiecczyzny  w Żywcu	" WHERE Lp=	387	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dewocjonaliów i Rzeczy Osobistych w Ostrowi Mazowieckiej (w organizacji)	" WHERE Lp=	388	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum 4 Pułku Strzelców Podhalańskich	" WHERE Lp=	389	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum II Korpusu Polskiego w Józefowie	" WHERE Lp=	390	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum II Wojny Światowej w Lubiszynie  (w organizacji)	" WHERE Lp=	391	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dawnej Wsi ,,Domek Tkaczki”	" WHERE Lp=	392	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dolina Psarki 	" WHERE Lp=	393	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dwór Feillów 	" WHERE Lp=	394	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Dziedzictwa Kulturowego  (w organizacji)	" WHERE Lp=	395	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum 3 Dywizji Piechoty Legionów w Zamościu (w organizacji)	" WHERE Lp=	396	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Eksploracji w Przeźmierowie	" WHERE Lp=	397	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Elwiro Michała Andriollego	" WHERE Lp=	398	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Etnograficzno - Archeologiczne KLEISTMETAL(w organizacji)	" WHERE Lp=	399	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Farmacji Apteki „Pod Łabędziem” w Bydgoszczy	" WHERE Lp=	400	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fiata 126p	" WHERE Lp=	401	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fort XII Werner w Żurawicy (w organizacji)	" WHERE Lp=	402	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fotografii w Janowie Lubelskim  (w organizacji)	" WHERE Lp=	403	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Frontu Wschodniego (w organizacji)	" WHERE Lp=	404	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Górnictwa i Historii Złotego Stoku (w organizacji)	" WHERE Lp=	405	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Góry Sowie Region Sudety w organizacji	" WHERE Lp=	406	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gród Średniowieczny w Brzeźniku (w organizacji)	" WHERE Lp=	407	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Bieszczad w Czarnej Górnej 	" WHERE Lp=	408	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii i Działań Zbrojnych (w organizacji)	" WHERE Lp=	409	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Gospodarki, Finansów i Rozwoju Przedsiębiorczości Na Ziemiach Polskich (w organizacji)	" WHERE Lp=	410	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Komputerów i Informatyki  (w organizacji)	" WHERE Lp=	411	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Modlina i Nowego Dworu Mazowieckiego (w organizacji)	" WHERE Lp=	412	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Ziemi Ciechanowskiej (w organizacji)	" WHERE Lp=	413	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Broni Pancernej  (w organizacji)	" WHERE Lp=	414	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne ,,Frontu Wschodniego”  (w organizacji)	" WHERE Lp=	415	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Północne Mazowsze i Garnizon Różan 1914- 1945  (w organizacji)	" WHERE Lp=	416	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Sulejówku (w organizacji)	" WHERE Lp=	417	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne Warszawa Kampinos 1939 (w organizacji)	" WHERE Lp=	418	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne - Zespół Pałacowy  w Patrykozach  (w organizacji)	" WHERE Lp=	419	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczno-Etnograficzne w Andrychowie	" WHERE Lp=	420	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczno Etnograficzne w Osieku (w organizacji)	" WHERE Lp=	421	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczno – Przyrodnicze ,,Pamiątka”	" WHERE Lp=	422	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Historyczny Dolny Śląsk (w organizacji)	" WHERE Lp=	423	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historycznych Pojazdów Militarnych  i Techniki Motoryzacyjnej w Boczkach	" WHERE Lp=	424	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Humoru i Absurdu w Poznaniu (w organizacji)	" WHERE Lp=	425	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ikon i Kultury Staroobrzędowców  (w organizacji)	" WHERE Lp=	426	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. Michała Drzymały w Miasteczku Krajeńskim (w organizacji)	" WHERE Lp=	427	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. mjr. Władysława Nowakowskiego ,,Żubra”	" WHERE Lp=	428	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Jednostek Specjalnych i Wojsk Powietrzno - Desantowych (w organizacji) 	" WHERE Lp=	429	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kaszubska Zagroda Bielickowo  (w organizacji)	" WHERE Lp=	430	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kart do Gry (w organizacji)	" WHERE Lp=	431	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kolekcji Dwór Muławki   (w organizacji)	" WHERE Lp=	432	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kolekcji Macieja Głowackiego	" WHERE Lp=	433	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Komunikacji w Paterku (w organizacji)	" WHERE Lp=	434	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Konfliktów Zbrojnych w Warszawie (w organizacji)	" WHERE Lp=	435	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kowalstwa i Ślusarstwa Mierzwińskich w Hajnówce	" WHERE Lp=	436	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kresów i Ziemi Ostrowskiej im. Marzeny i Zbigniewa Banaszków w Ostrowi Mazowieckiej (w organizacji)	" WHERE Lp=	437	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kultury Romów w Warszawie   (w organizacji)	" WHERE Lp=	438	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lalek w Pilźnie	" WHERE Lp=	439	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lisewski Zakątek w Lisewie (w organizacji)	" WHERE Lp=	440	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lwóweckie w Lwówku Śląskim (w organizacji)	" WHERE Lp=	441	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Łączności w Redzie  (w organizacji)	" WHERE Lp=	442	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta Słupska 	" WHERE Lp=	443	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Militariów „Atena” w Skwierzynie   (w organizacji)	" WHERE Lp=	444	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Militariów i Artefaktów w Brodnicy (w organizacji)	" WHERE Lp=	445	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Militarnej Historii w Bornem Sulinowie	" WHERE Lp=	446	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Mineralogiczne ze zbiorów Renaty Sokołowskiej w Szklarskiej Porębie	" WHERE Lp=	447	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miniaturowej Sztuki Profesjonalnej Henryk Jan Dominiak w Tychach 	" WHERE Lp=	448	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Młynarstwa i Rolnictwa w Osiecznej	" WHERE Lp=	449	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Młynarstwa, Techniki i Rzemiosła Wiejskiego im. Józefa Winiarskiego (w organizacji)	" WHERE Lp=	450	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motocykli Zabytkowych w Stężycy 	" WHERE Lp=	451	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji   (w organizacji)	" WHERE Lp=	452	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji i Techniki SKARB NARODU w Warszawie (w organizacji)	" WHERE Lp=	453	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji i Techniki w Opaczy Kolonii  (w organizacji)	" WHERE Lp=	454	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji i Techniki w Radomiu (w organizacji)	" WHERE Lp=	455	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji i Wojskowości w Tanowie (w organizacji)	" WHERE Lp=	456	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Motoryzacji w Bystrej (w organizacji)	" WHERE Lp=	457	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Narwi w Tykocinie (w organizacji)	" WHERE Lp=	458	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Obrony Wybrzeża w Świnoujściu	" WHERE Lp=	459	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Operacji i Działań Specjalnych (w organizacji)	" WHERE Lp=	460	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża i Techniki Użytkowej im. ks. gen. Stanisława Brzóski w Łukowie  (w organizacji)	" WHERE Lp=	461	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża i Techniki Ziemi Zamojskiej  (w organizacji)	" WHERE Lp=	462	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża im. Oddziałów Partyzanckich Ziemi Opatowskiej w Męczennicach  (w organizacji)	" WHERE Lp=	463	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pacowa Chata w Krypnie Wielkim (w organizacji)	" WHERE Lp=	464	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pałacowe Garnizonu Biedrusko (w organizacji)	" WHERE Lp=	465	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum ,,Patria Colbergiensis” w Kołobrzegu 	" WHERE Lp=	466	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Piśmiennictwa i Drukarstwa w Grębocinie	" WHERE Lp=	467	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pojazdów Historycznych „Polskie Drogi” w Busku – Zdroju (w organizacji)	" WHERE Lp=	468	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pojazdów Militarnych i Uzbrojenia (w organizacji)	" WHERE Lp=	469	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pojazdów Militarnych w Częstochowie (w organizacji)	" WHERE Lp=	470	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Polskiej Motoryzacji XX wieku ,,Polska na Kołach” w Busku – Zdroju (w organizacji)	" WHERE Lp=	471	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pól Bitewnych Pomorza (w organizacji)	" WHERE Lp=	472	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum 1 Pułku Strzelców Konnych   w Garwolinie                                                                                    (w organizacji)	" WHERE Lp=	473	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przedmiotów Historycznych i Zapomnianych	" WHERE Lp=	474	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przemysłu i Kolejnictwa na Śląsku	" WHERE Lp=	475	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przemysłu Wojennego w Pogórzu   (w organizacji)	" WHERE Lp=	476	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przyrodnicze w Turzynie (w organizacji)	" WHERE Lp=	477	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Radiotechniki (w organizacji)	" WHERE Lp=	478	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne Jama Michalików w Serocku (w organizacji)	" WHERE Lp=	479	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Kierzkowie	" WHERE Lp=	480	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Ruks Młynie  (w organizacji)	" WHERE Lp=	481	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalnego Pogranicza i Międzyrzeckiego Rejonu Umocnionego  w Kaławie (w organizacji)	" WHERE Lp=	482	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Saperskie „Explosive” (w organizacji)	" WHERE Lp=	483	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum - Skansen Młynarstwa w Żukowie (w organizacji) 	" WHERE Lp=	484	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum – Skansen w Ochabach – Tradycyjna Zagroda Rolna 	" WHERE Lp=	485	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Służb Mundurowych w Gdańsku (w organizacji)	" WHERE Lp=	486	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Spadochroniarstwa i Wojsk Specjalnych w organizacji 	" WHERE Lp=	487	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sprzętu Wojskowego w Mrągowie	" WHERE Lp=	488	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sprzętu Wojskowego we Wrocławiu (w organizacji)	" WHERE Lp=	489	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Strategii i Taktyki Działań Zbrojnych CLAUSEWITZ (w organizacji)	" WHERE Lp=	490	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Inżynierskiej  KOPRAS w Fiałkowie (w organizacji)	" WHERE Lp=	491	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Polskiej w Sopocie	" WHERE Lp=	492	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Śląskiego Września 1939 roku   (w organizacji)	" WHERE Lp=	493	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Światowego Oręża i Wojskowości w organizacji	" WHERE Lp=	494	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Bojowej w Olszynie  (w organizacji)	" WHERE Lp=	495	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Machin Wojennych w Gnieźnie	" WHERE Lp=	496	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Rzemiosła (w organizacji)	" WHERE Lp=	497	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Rzemiosła Wiejskiego  w Zapuście (w organizacji)	" WHERE Lp=	498	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Techniki Wojskowej ,,TYTAN,, (w organizacji)	" WHERE Lp=	499	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej (w organizacji)	" WHERE Lp=	500	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej i Cywilnej ,,MARS,, (w organizacji)	" WHERE Lp=	501	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Rzemiosła Ślusarstwo – Kowalstwo w organizacji 	" WHERE Lp=	502	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej i Użytkowej w Bytomiu (w organizacji)	" WHERE Lp=	503	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej i Użytkowej  w Zabrzu (w organizacji)	" WHERE Lp=	504	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Motoryzacyjnej 	" WHERE Lp=	505	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Uzbrojenia w Bydgoszczy  (w organizacji)	" WHERE Lp=	506	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Uzbrojenia w Kamiennej Górze (w organizacji)	" WHERE Lp=	507	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej ARMA w Warszawie	" WHERE Lp=	508	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej i Motoryzacji w Góralach w organizacji 	" WHERE Lp=	509	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej i Obrony Przeciwlotniczej w Busku - Zdroju  (w organizacji)	" WHERE Lp=	510	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej i Użytkowej 	" WHERE Lp=	511	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej im. Bogdana Wojciecha Kozłowskiego w Olsztynie 	" WHERE Lp=	512	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej im. Jerzego Tadeusza Widuchowskiego w Zabrzu   (w organizacji)	" WHERE Lp=	513	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej w Feliksowie (w organizacji) 	" WHERE Lp=	514	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej w Jaworznie (w organizacji)	" WHERE Lp=	515	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej w Kłodawie (w organizacji)	" WHERE Lp=	516	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tradycji Ruchu Narodowego w Jelczu - Laskowicach (w organizacji)	" WHERE Lp=	517	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Twierdza BTR – 40  we Wrocławiu	" WHERE Lp=	518	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Uzbrojenia (w organizacji)	" WHERE Lp=	519	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Uzbrojenia i Wojskowości (w organizacji)	" WHERE Lp=	520	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Uzbrojenia Żołnierza Wojska Polskiego 1914-1945 (w organizacji)	" WHERE Lp=	521	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Volkswagena	" WHERE Lp=	522	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum VOLVO i innych Automobili w Poznaniu Volvostrada (w organizacji) 	" WHERE Lp=	523	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum w Ponurzycy (w organizacji)	" WHERE Lp=	524	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Willa Lodusieńka w Warszawie 	" WHERE Lp=	525	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojen i Życia (w organizacji)	" WHERE Lp=	526	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojny i Pokoju (w organizacji)	" WHERE Lp=	527	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojny Obronnej Rybnik’39  (w organizacji)	" WHERE Lp=	528	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojskowe i Regionalne w Klenicy (w organizacji)	" WHERE Lp=	529	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojskowo- Cywilne w Łosicach 	" WHERE Lp=	530	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojskowości i Uzbrojenia (w organizacji)	" WHERE Lp=	531	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wojskowości w Świerklańcu (w organizacji)	" WHERE Lp=	532	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wolnego Czasu (w organizacji)	" WHERE Lp=	533	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi Sudeckiej i Techniki Militarnej	" WHERE Lp=	534	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wsi w Maruszowie (w organizacji)	" WHERE Lp=	535	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Współczesnej Broni Palnej w Jeżowie Sudeckim (w organizacji)	" WHERE Lp=	536	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zabawek w Kudowie Zdroju   (w organizacji)	" WHERE Lp=	537	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zabytków Techniki Wojskowej w Warszawie	" WHERE Lp=	538	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamkowe Kamieniec	" WHERE Lp=	539	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamkowe w Grodźcu	" WHERE Lp=	540	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum ,,Ziemi Kaszubskiej i Sprzętów Militarnych” (w organizacji)	" WHERE Lp=	541	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Makowskiej i Garnizonu Różan	" WHERE Lp=	542	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Przemkowskiej (w organizacji)	" WHERE Lp=	543	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Włodawskiej	" WHERE Lp=	544	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziemi Wolsztyńskiej  (w organizacji)	" WHERE Lp=	545	;
UPDATE mytable set Nazwa_Muzeum =  "	Nadwiślańskie Muzeum Broni Dawnej i Nowej w Piasecznie (w organizacji)	" WHERE Lp=	546	;
UPDATE mytable set Nazwa_Muzeum =  "	Podlaskie Muzeum Techniki Wojskowej  i Użytkowej w Bielanach Wąsach 	" WHERE Lp=	547	;
UPDATE mytable set Nazwa_Muzeum =  "	Pomorskie Muzeum Motoryzacji  (w organizacji)	" WHERE Lp=	548	;
UPDATE mytable set Nazwa_Muzeum =  "	Pomorskie Muzeum Motoryzacji i Techniki  w Gdyni (w organizacji)	" WHERE Lp=	549	;
UPDATE mytable set Nazwa_Muzeum =  "	Pomorskie Okręgowe Muzeum PRL w Sępólnie Krajeńskim (w organizacji)	" WHERE Lp=	550	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Multimedialne Muzeum Gry i Zabawy w Warszawie (w organizacji)	" WHERE Lp=	551	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Broni i Militariów w Świdnicy	" WHERE Lp=	552	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Broni Pancernej i Militariów im. Franciszka Bier w Bielsku-Białej	" WHERE Lp=	553	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Historyczne Gaja w Janowie (w organizacji)	" WHERE Lp=	554	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Kowalstwa w Warszawie	" WHERE Lp=	555	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Militarne w Woli Małej (w organizacji)	" WHERE Lp=	556	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Motoryzacji i Techniki   w Otrębusach	" WHERE Lp=	557	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Podkarpackich Pól Bitewnych	" WHERE Lp=	558	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Pojazdów Militarnych  i Zabytkowych w Rakszawie	" WHERE Lp=	559	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Polsko-Amerykańskie „Hell’s Angel” w Wadowicach	" WHERE Lp=	560	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Sztuki Ludowej  w Otrębusach	" WHERE Lp=	561	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum Techniki i Militariów w Rzeszowie	" WHERE Lp=	562	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum „Tomala” w Kadzidle	" WHERE Lp=	563	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum w Petrykozach	" WHERE Lp=	564	;
UPDATE mytable set Nazwa_Muzeum =  "	Prywatne Muzeum w Tuklęczy (w organizacji)	" WHERE Lp=	565	;
UPDATE mytable set Nazwa_Muzeum =  "	Regionalne Muzeum Drogownictwa „Nurzec Stacja”	" WHERE Lp=	566	;
UPDATE mytable set Nazwa_Muzeum =  "	Śląskie Muzeum Militariów i Techniki Użytkowej w Gorzycach  (w organizacji)	" WHERE Lp=	567	;
UPDATE mytable set Nazwa_Muzeum =  "	Świętokrzyskie Muzeum Militariów  w Małogoszczu (w organizacji)	" WHERE Lp=	568	;
UPDATE mytable set Nazwa_Muzeum =  "	Toruńskie Muzeum Oręża   (w organizacji)	" WHERE Lp=	569	;
UPDATE mytable set Nazwa_Muzeum =  "	TWIERDZA TORUŃ-Muzeum Historii i Wojskowości w Toruniu	" WHERE Lp=	570	;
UPDATE mytable set Nazwa_Muzeum =  "	Unisławskie Muzeum Barwy i Broni   (w organizacji)	" WHERE Lp=	571	;
UPDATE mytable set Nazwa_Muzeum =  "	Zagłębiowskie Muzeum Militariów Dragon w Sosnowcu (w organizacji)	" WHERE Lp=	572	;
UPDATE mytable set Nazwa_Muzeum =  "	Dolnośląskie Społeczne Muzeum Kolejnictwa Przy Klubie Sympatyków Kolei we Wrocławiu	" WHERE Lp=	573	;
UPDATE mytable set Nazwa_Muzeum =  "	Europejskie Centrum - Muzeum Haftu na Ziemi Garkowskiej	" WHERE Lp=	574	;
UPDATE mytable set Nazwa_Muzeum =  "	Interaktywne Muzeum Technik Bezpieczeństwa, Transportu, Ochrony i Higieny Pracy w Mikołowie	" WHERE Lp=	575	;
UPDATE mytable set Nazwa_Muzeum =  "	Kujawskie Muzeum Oręża, Nauki i Techniki (w organizacji)	" WHERE Lp=	576	;
UPDATE mytable set Nazwa_Muzeum =  "	Małopolskie Muzeum Pożarnictwa  im. Z. Gęsikowskiego w Alwerni	" WHERE Lp=	577	;
UPDATE mytable set Nazwa_Muzeum =  "	Mazurskie Muzeum Militariów 	" WHERE Lp=	578	;
UPDATE mytable set Nazwa_Muzeum =  "	Mobilne Muzeum Lotnictwa i Techniki w Warszawie (w organizacji)	" WHERE Lp=	579	;
UPDATE mytable set Nazwa_Muzeum =  "	Mobilne Muzeum Militarne we Wrocławiu (w organizacji)	" WHERE Lp=	580	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Akademii Sztuk Pięknych                                                                        w Warszawie	" WHERE Lp=	581	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Bambrów Poznańskich	" WHERE Lp=	582	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Brodnickiej Grupy Eksploracyjno -Poszukiwawczej (w organizacji) 	" WHERE Lp=	583	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni Dawnej i Nowej Towarzystwa Strzeleckiego	" WHERE Lp=	584	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni i Sprzętu Wojskowego Kwidzyńskiego Stowarzyszenia Sportowo-Kolekcjonerskiego GWARD	" WHERE Lp=	585	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Broni i Sprzętu Wojskowego SIRGUNE (w organizacji)	" WHERE Lp=	586	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Chirurgii i Sali Operacyjnej w Ustroniu 	" WHERE Lp=	587	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czynu Bojowego Kleeberczyków w Woli Gułowskiej (w organizacji)	" WHERE Lp=	588	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czynu Niepodległościowego 	" WHERE Lp=	589	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Czynu Zbrojnego w Krakowie Nowej Hucie	" WHERE Lp=	590	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Edukacji Pszczółki w Niezwojowicach 	" WHERE Lp=	591	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Eksploracji Polskiej (w organizacji)	" WHERE Lp=	592	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fortyfikacji Pancernej Twierdzy Toruń	" WHERE Lp=	593	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Fryderyka Chopina w Warszawie	" WHERE Lp=	594	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gazownictwa w Paczkowie	" WHERE Lp=	595	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gazownictwa w Warszawie	" WHERE Lp=	596	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Grodziska Kolej Drezynowa (w organizacji)	" WHERE Lp=	597	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Gryfa Pomorskiego	" WHERE Lp=	598	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Harcerstwa w Warszawie	" WHERE Lp=	599	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii i Uzbrojenia w Opolu przy Stowarzyszeniu 10 Sudeckiej Dywizji Zmechanizowanej (w organizacji)	" WHERE Lp=	600	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Medycyny Warszawskiego Uniwersytetu Medycznego (w organizacji)	" WHERE Lp=	601	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Obronności i Oręża Polskiego w Drzewcach  (w organizacji)	" WHERE Lp=	602	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Ruchu Harcerskiego (w organizacji)	" WHERE Lp=	603	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Szczypiorna 	" WHERE Lp=	604	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historii Twierdzy Świnoujście	" WHERE Lp=	605	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne im. 7 Pułku Lansjerów Nadwiślańskich (w organizacji)	" WHERE Lp=	606	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne „Skarb” w Policach	" WHERE Lp=	607	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne przy PBG Spółka Akcyjna	" WHERE Lp=	608	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Historyczne w Bytomiu (w organizacji)	" WHERE Lp=	609	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Hutnictwa Cynku - Walcownia	" WHERE Lp=	610	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Hutnictwa Doliny Małej Panwi	" WHERE Lp=	611	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum im. G. i. J. Osiakowskich (w organizacji)	" WHERE Lp=	612	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Instytutu Tarnogórskiego 	" WHERE Lp=	613	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kampanii Wrześniowej i Twierdzy Modlin	" WHERE Lp=	614	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Katolickiego Uniwersytetu Lubelskiego Jana Pawła II (w organizacji)	" WHERE Lp=	615	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kierownictwa Dywersji Armii Krajowej w Stalowej Woli - Rozwadowie (w organizacji)	" WHERE Lp=	616	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kolekcji im. Jana Pawła II Fundacji Carroll-Porczyńskich w Warszawie	" WHERE Lp=	617	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Kolekcja Sztuki Współczesnej	" WHERE Lp=	618	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Komunikacji w Warszawie (w organizacji) 	" WHERE Lp=	619	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Książki Artystycznej w Łodzi	" WHERE Lp=	620	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lokalne Kolejki Szprotawskiej w Zielonej Górze (w organizacji)	" WHERE Lp=	621	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lotnictwa i Techniki Militarnej w Rogowie	" WHERE Lp=	622	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lotnictwa Ziemi Świdwińskiej (w organizacji)	" WHERE Lp=	623	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lotnicze w Góraszce	" WHERE Lp=	624	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Lwowa i Kresów Południowo-Wschodnich (w organizacji)	" WHERE Lp=	625	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Marii Skłodowskiej - Curie Polskiego Towarzystwa Chemicznego	" WHERE Lp=	626	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miasta i Rzeki Warty przy Oddziale PTTK im. dr E. Kaleniewicz w Warcie	" WHERE Lp=	627	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Miejskie w Górowie Iławeckim 	" WHERE Lp=	628	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Militarnych Dziejów Śląska w Pszczynie (w organizacji)	" WHERE Lp=	629	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Morskiego Dywizjonu Lotniczego w Pucku	" WHERE Lp=	630	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Nauk Rolniczych im. Książąt Czartoryskich w Puławach (w organizacji)	" WHERE Lp=	631	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Obrony Wybrzeża	" WHERE Lp=	632	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża i Techniki Użytkowej	" WHERE Lp=	633	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Oręża Polskiego im. 1. Brygady Pancernej im. Bohaterów Westerplatte	" WHERE Lp=	634	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum „Otwarta Twierdza”-Otwarte Rozproszone Ekomuzeum Cywilizacji i Wojny XIX i XX wieku	" WHERE Lp=	635	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pamiątek Turystycznych PTTK w Radomiu	" WHERE Lp=	636	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pamięci Narodowej Kobiet Polskich  w Szczecinie   (w organizacji)	" WHERE Lp=	637	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Papiernictwa w Dawnej Królewskiej Fabryce Papieru w Konstancinie-Jeziornie	" WHERE Lp=	638	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Parowozownia Jarocin w Jarocinie  (w organizacji)	" WHERE Lp=	639	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum „Pod Kuźniczym Młotem”  	" WHERE Lp=	640	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Polskiego Czynu Zbrojnego w Armiach Sprzymierzonych (w organizacji)	" WHERE Lp=	641	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Powozów Galowice	" WHERE Lp=	642	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Pożarnictwa  w Przodkowie	" WHERE Lp=	643	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum PRL-u i Historii Miasta Nowy Dwór Mazowiecki (w organizacji)	" WHERE Lp=	644	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przemysłu i Techniki w Wałbrzychu 	" WHERE Lp=	645	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Przemysłu Zapałczanego w Częstochowie	" WHERE Lp=	646	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ratownictwa w Krakowie 	" WHERE Lp=	647	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne im. Seweryna Udzieli w Starym Sączu	" WHERE Lp=	648	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne PTTK im. Antoniego Minkiewicza w Olkuszu	" WHERE Lp=	649	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne PTTK im. Ignacego Łukasiewicza w Gorlicach	" WHERE Lp=	650	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne PTTK im. Izabeli Ks. Czartoryskiej w Puławach 	" WHERE Lp=	651	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne PTTK im. Władysława Kowalskiego w Dobczycach	" WHERE Lp=	652	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne PTTK w Końskich	" WHERE Lp=	653	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Brzesku (w organizacji)	" WHERE Lp=	654	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Dobrodzieniu (w organizacji)	" WHERE Lp=	655	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Goczałkowicach-Zdroju (w organizacji)	" WHERE Lp=	656	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Handzlówce	" WHERE Lp=	657	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Krokowej	" WHERE Lp=	658	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Regionalne w Pilźnie	" WHERE Lp=	659	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Romanowscy w organizacji z siedzibą w Poznaniu 	" WHERE Lp=	660	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sali BHP Stoczni Gdańskiej (w organizacji)	" WHERE Lp=	661	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Spraw Wojskowych w Krakowie 	" WHERE Lp=	662	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sue Ryder 	" WHERE Lp=	663	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Drukarskiej i Papiernictwa  im. Fiola i Fiodorowa w Supraślu  (w organizacji)	" WHERE Lp=	664	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Książki	" WHERE Lp=	665	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Sztuki Reduktywnej	" WHERE Lp=	666	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Przemysłu NOT w Warszawie	" WHERE Lp=	667	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Sztuki Wojennej  (w organizacji)	" WHERE Lp=	668	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Uzbrojenia Stowarzyszenia Strzelecko Kolekcjonerskiego Olimp w Olimpinie (w organizacji)	" WHERE Lp=	669	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki i Uzbrojenia Wojskowego w Kaliszu przy Stowarzyszeniu Strzeleckim ,,Bellona” (w organizacji)	" WHERE Lp=	670	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej i Historii Pomorza w Kłaninie (w organizacji)	" WHERE Lp=	671	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej Riese	" WHERE Lp=	672	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Militarnej w Warszawie (w organizacji)	" WHERE Lp=	673	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Rolniczej w Bierkowie (w organizacji)	" WHERE Lp=	674	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej ,,GRYF”	" WHERE Lp=	675	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej i Tradycji Jednostki Strzeleckiej 4008 Łódź	" WHERE Lp=	676	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Techniki Wojskowej przy Stowarzyszeniu Miłośników Sprzętu Pancernego „SKOT” w Środzie Wielkopolskiej 	" WHERE Lp=	677	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tercetu Egzotycznego w Lubiniu (w organizacji)	" WHERE Lp=	678	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tradycji i Techniki w organizacji 	" WHERE Lp=	679	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tradycji Kolejowej w Węgorzewie 	" WHERE Lp=	680	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Tradycji Rybactwa Stawów Milickich i Doliny Baryczy (w organizacji)	" WHERE Lp=	681	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Twierdzy Modlin w organizacji 	" WHERE Lp=	682	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Twierdzy Przemyśl (w organizacji)	" WHERE Lp=	683	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Uniwersytetu Jagiellońskiego	" WHERE Lp=	684	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Uzbrojenia w Stanisławowie (w organizacji)	" WHERE Lp=	685	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wału Pomorskiego i Militarnej Historii Pomorza w Szczecinku                             	" WHERE Lp=	686	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wału Pomorskiego w Wałczu  (w organizacji) 	" WHERE Lp=	687	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wisły Środkowej i Ziemi Wyszogrodzkiej	" WHERE Lp=	688	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Witrażu	" WHERE Lp=	689	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Wydziału Nauk o Ziemi Uniwersytetu Śląskiego w Katowicach	" WHERE Lp=	690	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamek w Rydzynie (w organizacji)	" WHERE Lp=	691	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum-Zamek w Baranowie Sandomierskim	" WHERE Lp=	692	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Zamku w Chudowie	" WHERE Lp=	693	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum-Zespół Zamkowy w Niedzicy	" WHERE Lp=	694	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Ziem Nadbużańskich – Zespół Pałacowy Ossolińskich Sterdyń  (w organizacji)	" WHERE Lp=	695	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Żołnierzy Wyklętych i Więźniów Politycznych PRL	" WHERE Lp=	696	;
UPDATE mytable set Nazwa_Muzeum =  "	Muzeum Żywej Historii (w organizacji)	" WHERE Lp=	697	;
UPDATE mytable set Nazwa_Muzeum =  "	Ośrodek Dokumentacji i Historii Ziemi Żmigrodzkiej - Muzeum im. Leona Karcińskiego w Nowym Żmigrodzie                                                                                                   (w organizacji)	" WHERE Lp=	698	;
UPDATE mytable set Nazwa_Muzeum =  "	Pałuckie Muzeum Techniki Wojskowej i Uzbrojenia w Kowalewku	" WHERE Lp=	699	;
UPDATE mytable set Nazwa_Muzeum =  "	Pilskie Muzeum Wojskowe (w organizacji)	" WHERE Lp=	700	;
UPDATE mytable set Nazwa_Muzeum =  "	Podkarpackie Muzeum Konia imieniem BASK (w organizacji)	" WHERE Lp=	701	;
UPDATE mytable set Nazwa_Muzeum =  "	Podlaskie Muzeum Militariów w Białymstoku (w organizacji)	" WHERE Lp=	702	;
